# -*- coding: utf-8 -*-
"""FER_CNN_Model_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LEhk8ZVKEK9LrOb43HJKkhCqS1AHf6yE

# FER CNN — Google Colab Notebook
"""

# SETUP 
import os, math, random, itertools
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

print("TensorFlow:", tf.__version__)

"""## 2) Load dataset


"""

# LOAD DATA 
CSV_PATH = "train.csv"

df = pd.read_csv(CSV_PATH)
display(df.head())
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

"""## 3) Remove *Disgust* and remap labels

FER2013 label mapping is typically:
- 0=Angry, 1=Disgust, 2=Fear, 3=Happy, 4=Sad, 5=Surprise, 6=Neutral



"""

# REMOVE DISGUST 
DISGUST_LABEL = 1

if "emotion" not in df.columns or "pixels" not in df.columns:
    raise ValueError("Expected columns: 'emotion' and 'pixels'. Found: " + str(df.columns.tolist()))

# Remove disgust rows
df = df[df["emotion"] != DISGUST_LABEL].copy()
print("After removing disgust:", df.shape)

# Remap remaining labels
unique_labels = sorted(df["emotion"].unique().tolist())
label_map = {old:i for i, old in enumerate(unique_labels)}
inv_label_map = {v:k for k,v in label_map.items()}

df["label"] = df["emotion"].map(label_map).astype(int)
num_classes = df["label"].nunique()

print("Unique original labels (after removal):", unique_labels)
print("Label map:", label_map)
print("Num classes:", num_classes)

from google.colab import drive
drive.mount('/content/drive')

"""## 4) Parse pixels ➜ images


"""

# PARSE PIXELS 
IMG_SIZE = 48  # FER2013 is 48x48

def pixels_to_image(pixels_str, img_size=IMG_SIZE):
    arr = np.fromstring(pixels_str, sep=" ", dtype=np.float32)
    if arr.size != img_size * img_size:
        raise ValueError(f"Unexpected pixel count {arr.size}. Expected {img_size*img_size}. "
                         f"Update IMG_SIZE if your data isn't {img_size}x{img_size}.")
    arr = arr.reshape((img_size, img_size, 1))
    return arr

# Sanity check (first row)
sample_img = pixels_to_image(df.iloc[0]["pixels"])
print("Sample image shape:", sample_img.shape, "min/max:", sample_img.min(), sample_img.max())

"""## 5) Train/Val split



"""

# SPLIT 
from sklearn.model_selection import train_test_split

if "label" not in df.columns:
    raise ValueError("Expected df['label'] to exist")

train_df, val_df = train_test_split(
    df,
    test_size=0.15,
    random_state=42,
    stratify=df["label"]
)

print("Train size:", len(train_df), "Val size:", len(val_df))
print("Train label counts:\n", train_df["label"].value_counts().sort_index())
print("Val label counts:\n", val_df["label"].value_counts().sort_index())

"""## 6) Build tf.data pipeline with augmentation



"""

# DATA PIPELINE 
AUTOTUNE = tf.data.AUTOTUNE
BATCH_SIZE = 64

def make_dataset(dataframe, training: bool):
    pixels = dataframe["pixels"].values
    labels = dataframe["label"].values.astype(np.int32)

    def gen():
        for p, y in zip(pixels, labels):
            img = pixels_to_image(p)
            yield img, y

    ds = tf.data.Dataset.from_generator(
        gen,
        output_signature=(
            tf.TensorSpec(shape=(IMG_SIZE, IMG_SIZE, 1), dtype=tf.float32),
            tf.TensorSpec(shape=(), dtype=tf.int32)
        )
    )

    # Normalize to 0..1
    ds = ds.map(lambda x,y: (x/255.0, y), num_parallel_calls=AUTOTUNE)

    if training:
        # FER augmentations
        aug = keras.Sequential([
            layers.RandomFlip("horizontal"),
            layers.RandomTranslation(0.08, 0.08),
            layers.RandomZoom(0.10, 0.10),
            layers.RandomContrast(0.15),
        ])
        ds = ds.map(lambda x,y: (aug(x, training=True), y), num_parallel_calls=AUTOTUNE)
        ds = ds.shuffle(4096, reshuffle_each_iteration=True)

    ds = ds.batch(BATCH_SIZE).prefetch(AUTOTUNE)
    return ds

train_ds = make_dataset(train_df, training=True)
val_ds   = make_dataset(val_df, training=False)

"""## 7) Class weights"""

# CLASS WEIGHTS 
from sklearn.utils.class_weight import compute_class_weight

classes = np.arange(num_classes)
cw = compute_class_weight(class_weight="balanced", classes=classes, y=train_df["label"].values)
class_weights = {i: float(w) for i, w in enumerate(cw)}
print("Class weights:", class_weights)

"""## 8) CNN Model

"""

#  MODEL 
def conv_block(x, filters, kernel=3, drop=0.20, l2=1e-4):
    x = layers.Conv2D(filters, kernel, padding="same",
                      kernel_regularizer=keras.regularizers.l2(l2))(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)

    x = layers.Conv2D(filters, kernel, padding="same",
                      kernel_regularizer=keras.regularizers.l2(l2))(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)

    x = layers.MaxPooling2D()(x)
    x = layers.Dropout(drop)(x)
    return x

inputs = keras.Input(shape=(IMG_SIZE, IMG_SIZE, 1))
x = inputs

x = conv_block(x, 32, drop=0.20, l2=1e-4)
x = conv_block(x, 64, drop=0.25, l2=1e-4)
x = conv_block(x, 128, drop=0.30, l2=1e-4)

# extra block if underfitting occurs
# x = conv_block(x, 192, drop=0.35, l2=1e-4)

x = layers.Conv2D(256, 3, padding="same", kernel_regularizer=keras.regularizers.l2(1e-4))(x)
x = layers.BatchNormalization()(x)
x = layers.Activation("relu")(x)

x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.35)(x)

outputs = layers.Dense(num_classes, activation="softmax")(x)

model = keras.Model(inputs, outputs)
model.summary()

"""## 9) Train



"""

#  TRAIN 
EPOCHS = 60

try:
    optimizer = keras.optimizers.AdamW(learning_rate=3e-4, weight_decay=1e-4)
    print("Using AdamW")
except Exception:
    optimizer = keras.optimizers.Adam(learning_rate=3e-4)
    print("Using Adam")

model.compile(
    optimizer=optimizer,
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

callbacks = [
    keras.callbacks.EarlyStopping(monitor="val_accuracy", patience=10, restore_best_weights=True),
    keras.callbacks.ReduceLROnPlateau(monitor="val_loss", patience=3, factor=0.5, min_lr=1e-6, verbose=1),
    keras.callbacks.ModelCheckpoint("best_model.keras", monitor="val_accuracy", save_best_only=True, verbose=1),
]

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
    class_weight=class_weights,
    callbacks=callbacks,
    verbose=1
)

"""## 10) Learning curves"""

# CURVES 
hist = history.history
plt.figure()
plt.plot(hist["loss"], label="train_loss")
plt.plot(hist["val_loss"], label="val_loss")
plt.legend()
plt.title("Loss")
plt.show()

plt.figure()
plt.plot(hist["accuracy"], label="train_acc")
plt.plot(hist["val_accuracy"], label="val_acc")
plt.legend()
plt.title("Accuracy")
plt.show()

"""## 11) Evaluation + Confusion Matrix"""

# EVALUATION
val_loss, val_acc = model.evaluate(val_ds, verbose=0)
print(f"Validation accuracy: {val_acc:.4f}  |  val loss: {val_loss:.4f}")

# Predictions
y_true = val_df["label"].values.astype(int)
y_pred = np.argmax(model.predict(val_ds, verbose=0), axis=1)

from sklearn.metrics import classification_report, confusion_matrix
print("\nClassification report:\n")
print(classification_report(y_true, y_pred, digits=4))

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(6,5))
plt.imshow(cm, cmap='Blues') 
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.colorbar()
plt.show()

print("Label mapping (new -> original):", inv_label_map)

"""## 12) Save model + mapping

"""

# SAVE 
import json

model.save("facial_model.keras")

with open("label_map.json", "w") as f:
    json.dump({"old_to_new": label_map, "new_to_old": inv_label_map}, f, indent=2)

print("Saved: facial_model.keras")


model.save('facial_model.h5')
print("Model saved as facial_model.h5")